name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
runs:
  using: 'node16' #Custom Javascript action using node runtime which is javascript runtime
  main: 'main.js' #Name of the file that should be executed as custom action  
