name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  cachingOnOrOff:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
    using: 'composite'
    steps:
      - name: Cache dependencies
        if: inputs.cachingOnOrOff == 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.cachingOnOrOff != 'true' #If we dont want to use caching then this step should execute
        run: npm ci
        shell: bash #When using run, we need to add shell: